---
- name: set operating system and application defaults
  plist:
    dest: "{{ item.domain }}"
    value: "{{ item.defaults }}"
    container: "{{ item.container | default(None) }}"
  with_items: "{{ osapp_defaults }}"
