---
- name: install ruby 1.9.3 for octopress
  command: rbenv install 1.9.3-p194 creates=~/.rbenv/versions/1.9.3-p194

- name: install bundler
  gem:
    name: bundler
    state: present
    executable: ~/.rbenv/versions/1.9.3-p194/bin/gem
    user_install: no

- name: clone the blog repository from github
  git:
    repo: git@github.com:fgimian/fgimian.github.com.git
    dest: ~/Development/blog
    version: source
    accept_hostkey: yes

- name: install all dependencies
  bundler:
    state: present
    chdir: "{{ '~/Development/blog' | expanduser }}"
    executable: ~/.rbenv/versions/1.9.3-p194/bin/bundle

- name: check if github pages has been setup
  stat: path=~/Development/blog/_deploy/.git
  register: deploy_git_path

- name: setup github pages
  shell: rake setup_github_pages['git@github.com:fgimian/fgimian.github.com']
  args:
    chdir: ~/Development/blog
  environment:
    PATH: ~/.rbenv/versions/1.9.3-p194/bin:{{ ansible_env.PATH }}
  when: not deploy_git_path.stat.exists
