---
- name: check health of local directories
  stat: path="{{ item.local_dir }}"
  register: local_dir_health_check
  with_items: "{{ cloud_settings }}"

- name: clean up any directories if required
  file: path="{{ item.1.local_dir }}" state=absent
  when: local_dir_health_check.results[item.0].stat.exists and
        not local_dir_health_check.results[item.0].stat.islnk
  with_indexed_items: "{{ cloud_settings }}"

- name: symlink directory to cloud storage
  file:
    dest: "{{ item.local_dir }}"
    src: "{{ cloud_app_config_dir }}/{{ item.cloud_subdir }}"
    state: link
  with_items: "{{ cloud_settings }}"
