---
- name: set operating system and application defaults
  plist: dest="{{ item.domain }}" value="{{ item.defaults }}"
  with_items: "{{ osapp_defaults }}"

- name: check the current timezone
  command: systemsetup -gettimezone
  changed_when: false
  become: yes
  become_method: sudo
  register: current_timezone

- name: set the timezone
  command: systemsetup -settimezone {{ timezone }}
  become: yes
  become_method: sudo
  when: "'{{ timezone }}' not in '{{ current_timezone.stdout }}'"

- name: check flags for the user library folder
  changed_when: false
  command: ls -lOd ~/Library
  register: library_flags

- name: unhide the user library folder
  command: chflags nohidden ~/Library
  when: "'hidden' in library_flags"

- name: create the development folder
  file: path=~/Development state=directory
