---
- name: brew taps
  homebrew_tap: tap={{ item }} state=present
  with_items: brew_taps

- name: brew packages
  homebrew: name={{ item }} state=latest
  with_items: brew_packages

- name: brew cask tap
  homebrew_tap: tap=caskroom/cask state=present

- name: brew cask package manager
  homebrew: name=brew-cask state=latest

- name: desktop cask applications
  homebrew_cask: name={{ item }} state=present
  with_items: brew_casks

- name: check that appstore applications exist
  stat: path="/Applications/{{ item }}.app/Contents/_MASReceipt/receipt"
  with_items: appstore_apps
  register: appstore_app_files

# Note that we're using with_indexed_items below to avoid lengthy stat output
# for each item during the playbook run
- name: desktop appstore applications
  fail: msg="Please install {{ appstore_app_files.results[item.0].item }} from the App Store"
  when: not appstore_app_files.results[item.0].stat.exists
  with_indexed_items: "{{ appstore_apps }}"
