---
- name: ensure the sublime text settings directories exist
  file: path="{{ item }}" state=directory
  with_items:
  - ~/Library/Application Support/Sublime Text 3/Installed Packages
  - ~/Library/Application Support/Sublime Text 3/Packages/User

- name: install sublime text package control
  get_url: url='http://packagecontrol.io/Package Control.sublime-package'
  args:
    dest: ~/Library/Application Support/Sublime Text 3/Installed Packages
    mode: 0644

# Please note that the Soda theme files (Espresso Soda.tmTheme and
# Monokai Soda.tmTheme) were obtained via the URL
# http://buymeasoda.github.com/soda-theme/extras/colour-schemes.zip
- name: install sublime text settings
  copy: src=files/sublimetext/Packages dest='~/Library/Application Support/Sublime Text 3'
