---
# Specify dot files or folders which are to be copied
macos_dotfiles:
  # Dotfiles
  - src: files/dotfiles/.bash_profile
    dest: ~/.bash_profile
  - src: files/dotfiles/.gitconfig
    dest: ~/.gitconfig
  - src: files/dotfiles/.config/fish/config.fish
    dest: ~/.config/fish/config.fish
  - src: files/dotfiles/.ipython/profile_default/ipython_config.py
    dest: ~/.ipython/profile_default/ipython_config.py
