---
# Python
- name: install python 3.x
  homebrew: name=python3 state=latest

- name: install python completion
  homebrew: name=pip-completion state=latest

# Note that we must install Python 2.7 and its packages last to ensure they
# become the defaults
- name: install python 3.x global packages
  pip: name={{ item }} state=latest executable=pip3
  with_items: "{{ packages }}"
