---
# Specify folders which are to be symlinked to cloud storage
cloud_settings:
  - cloud_subdir: Audio Hijack
    local_dir: ~/Library/Application Support/Audio Hijack
  - cloud_subdir: OpenEmu/BIOS
    local_dir: ~/Library/Application Support/OpenEmu/BIOS
  - cloud_subdir: OpenEmu/Bindings
    local_dir: ~/Library/Application Support/OpenEmu/Bindings
  - cloud_subdir: OpenEmu/Cores
    local_dir: ~/Library/Application Support/OpenEmu/Cores
  - cloud_subdir: OpenEmu/Game Library
    local_dir: ~/Library/Application Support/OpenEmu/Game Library
  - cloud_subdir: OpenEmu/Save States
    local_dir: ~/Library/Application Support/OpenEmu/Save States
