---
brew_taps:
  - homebrew/completions
  - homebrew/fuse
  - caskroom/fonts
  - caskroom/versions
  - rcmdnk/rcmdnkcask
  - fgimian/fgimian

brew_packages:
  # Unix Utilities
  - android-platform-tools
  - bash
  - ctags
  - curl
  - findutils
  - fish
  - git
  - gnu-sed
  - hugo
  - md5sha1sum
  - rlwrap
  - sassc
  - shellcheck
  - sshfs
  - tree
  - watch
  - wget
  - xz

  # Completions
  - bash-completion

brew_casks:
  # Fonts
  - font-source-code-pro
  - font-source-code-pro-for-powerline

  # Freeware
  - android-file-transfer
  - appcleaner
  - bestres
  - bootchamp
  - cog
  - dropbox
  - firefox
  - flux
  - google-chrome
  - macdown
  - miaforgmail
  - mplayerx
  - openemu-experimental
  - skype
  - slack
  - sourcetree
  - transmission
  - virtualbox

  # Commercial
  - 1password
  - audio-hijack
  - daisydisk
  - dash
  - entropy
  # Use my Cask of Microsoft Office which is locked to a checksum and helps
  # avoid additional downloads
  # - fgimian/fgimian/microsoft-office
  - textual
  - vmware-fusion

appstore_apps:
  # Freeware
  - OneDrive
  - Twitter

  # Commercial
  - Affinity Designer
  - Affinity Photo
  - BetterSnapTool
  - Clear
  - iStat Mini
  - Screenflow
  - World Clock
