---
software_brew_casks:
  # General Software

  # Fonts
  - font-source-code-pro
  - font-source-code-pro-for-powerline

  # Freeware
  - android-file-transfer
  - appcleaner
  - bestres
  - bootchamp
  - cog
  - dropbox
  - firefox
  - flux
  - gmail-notifier
  - google-chrome
  - macdown
  - mplayerx
  - openemu-experimental
  - skype
  - slack
  - sourcetree
  - transmission
  - vagrant
  - virtualbox
  - xld

  # Commercial
  - 1password
  - audio-hijack
  - daisydisk
  - dash
  - entropy
  - focus
  - forklift-beta
  - microsoft-office
  - textual
  - vmware-fusion

  # Music Production Software
  # TODO: Native Instruments Komplete

  # DAWs & Drivers
  - ableton-live-suite
  - audiomove
  - celemony-melodyne-editor
  - focusrite-control
  - novation-remote-sl-template-editor
  - ocenaudio
  - steinberg-cubase-pro
  - steinberg-cubase-pro-update

  # Plug-ins (Effect)
  # ArtsAcoustic BigRock crashes Cubase when mixed with other plugins \
  # such as ArtsAcoustic Reverb and Eos
  # - artsacoustic-bigrock
  # ArtsAcoustic CL Series is unstable and crashes Cubase upon instantiating
  # - artsacoustic-cl-series
  - artsacoustic-reverb
  - audio-damage-eos
  - cableguys-filtershaper
  - cableguys-volumeshaper
  - cytomic-the-drop
  - cytomic-the-glue
  - dada-life-sausage-fattener
  - dmgaudio-compassion
  - dmgaudio-dualism
  - dmgaudio-equality
  - dmgaudio-equick
  - dmgaudio-equilibrium
  - dmgaudio-essence
  - dmgaudio-expurgate
  - dmgaudio-limitless
  - dmgaudio-pitchfunk
  - eventide-2016-stereo-room
  - focusrite-red-plugin-suite
  # TODO: Find a way to make the Goodhertz installer only install CanOpener
  - goodhertz-canopener-studio
  - illformed-glitch
  - relab-lx480-complete
  - softube-amp-room-essentials
  - softube-drawmer-s73
  - softube-fet-compressor
  - softube-fix-flanger-and-doubler
  - softube-saturation-knob
  - softube-tsar-1r
  - softube-tube-delay
  - sonalksis-studio-one-bundle
  - soundtoys-5
  - studio-devil-amp-modeler-pro
  - u-he-mfm2
  - u-he-satin
  - u-he-uhbik
  - valhalladsp-valhallaspacemodulator
  - valhalladsp-valhallavintageverb
  - voxengo-deft-compressor-au-aax
  - voxengo-deft-compressor-vst-vst3
  - voxengo-elephant-au-aax
  - voxengo-elephant-vst-vst3
  - voxengo-glisseq-au-aax
  - voxengo-glisseq-vst-vst3
  - voxengo-msed-au-aax
  - voxengo-msed-vst-vst3
  - voxengo-span-au-aax
  - voxengo-span-vst-vst3
  - voxengo-voxformer-au-aax
  - voxengo-voxformer-vst-vst3

  # Plug-ins (Instrument)
  - lennardigital-sylenth1
  - novation-bass-station
  - reveal-sound-spire
  # TODO: Spectrasonics Omnisphere
  - steinberg-padshop
  - steinberg-padshop-update
  - steinberg-retrologue
  - synapse-audio-dune
  - u-he-hive
  - u-he-zebra
  - xfer-records-serum
  - xfer-records-serum-update
  - xfer-records-serumfx-update
