brew_taps:
  - caskroom/versions
  - caskroom/fonts

brew_packages:
  # Languages
  - nodejs

  # Unix Utilities
  - bash
  - bash-completion
  - curl
  - findutils
  - git
  - md5sha1sum
  - readline
  - tree
  - vim
  - wget

python_packages:
  - ipython
  - pip
  - setuptools
  - virtualenv

brew_casks:
  # Freeware
  - google-chrome
  - dropbox
  - firefox
  - flux
  - iterm2
  - github
  - macdown
  - mplayerx
  - font-source-code-pro
  - transmission
  - vox

  # Commercial
  - 1password
  - entropy
  - sublime-text3
  - transmit
  - vmware-fusion

appstore_apps:
  # Freeware
  - Slack
  - Twitter

  # Commercial
  - Clear
  - Pixelmator
  - Textual 5

os_defaults:
  # System Preferences
  - domain: Apple Global Domain
    values:
      # General / Appearance / Use dark menu bar and Dock
      - AppleInterfaceStyle -string Dark
      # Keyboard / Key Repeat
      - KeyRepeat -int 2
      # Keyboard / Delay Until Repeat
      - InitialKeyRepeat -int 25
      # Keyboard / Use all F1, F2, etc. keys as standard function keys
      - com.apple.keyboard.fnState -bool true

  # System Preferences / Accessibility
  - domain: com.apple.universalaccess
    values:
      # Zoom / Use scroll gesture with modifier keys to zoom
      - closeViewScrollWheelToggle -bool true
      # Display / Cursor size
      - mouseDriverCursorSize -float 1.25

  # System Preferences / Keyboard
  - domain: NSGlobalDomain
    values:
      # Shortcuts / Full Keyboard Access / All controls
      - AppleKeyboardUIMode -int 3

  # Dock
  - domain: com.apple.dock
    values:
      # Make hidden applications translucent in the dock
      - showhidden -bool true
      # Turn Magnification On
      - magnification -bool true
