brew_taps:
  - caskroom/versions
  - caskroom/fonts

brew_casks:
  # Freeware
  - google-chrome
  - dropbox
  - firefox
  - flux
  - iterm2
  - github
  - macdown
  - mplayerx
  - font-source-code-pro
  - transmission
  - vox

  # Commercial
  - 1password
  - entropy
  - sublime-text3
  - transmit
  - vmware-fusion

brew_packages:
  # Cask
  - brew-cask

  # Languages
  - nodejs

  # Unix Utilities
  - bash
  - bash-completion
  - curl
  - git
  - readline
  - tree
  - vim
  - wget

python_packages:
  - ipython
  - pip
  - setuptools
  - virtualenv

appstore_apps:
  - Clear
  - Pixelmator
  - Slack
  - Textual 5
  - Twitter

os_defaults:
  # System Preferences / Accessibility
  - domain: com.apple.universalaccess
    values:
      # Zeem / Use scroll gesture with modifier keys to zoom
      - key: closeViewScrollWheelToggle
        type: bool
        value: true
