- name: set operating system and application defaults
  command: "defaults write '{{ item.0.domain }}' {{ item.1 }}"
  changed_when: false
  with_subelements:
    - osapp_defaults
    - values

- name: check the current timezone
  command: systemsetup -gettimezone
  changed_when: false
  become: yes
  become_method: sudo
  register: current_timezone

- name: set the timezone
  command: systemsetup -settimezone {{ timezone }}
  become: yes
  become_method: sudo
  when: "'{{ timezone }}' not in '{{ current_timezone.stdout }}'"

- name: check flags for the ~/Library folder
  changed_when: false
  command: ls -lOd ~/Library
  register: library_flags

- name: unhide the ~/Library folder
  command: chflags nohidden ~/Library
  when: "'hidden' in library_flags"
