---
- name: install docker
  homebrew: name={{ item }} state=latest
  with_items:
    - docker
    - docker-machine

- name: create a default virtual machine to run docker images
  command: docker-machine create --driver virtualbox default
  args:
    creates: ~/.docker/machine/machines/default
  notify:
    - stop default docker machine

- name: install kitematic
  homebrew_cask: name=kitematic state=present
