---
- name: install rbenv
  homebrew: name={{ item }} state=latest
  with_items:
    - rbenv
    - ruby-build

- name: install ruby completion
  homebrew: name={{ item }} state=latest
    - ruby-completion
    - rake-completion
